---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
    customize:
      cpus: 2
      memory: 1024
  run_list:
  - recipe[apt]
suites:
- name: mongod-recipe
  run_list:
    - recipe[hipsnip-mongodb_test::mongod_recipe]
    - recipe[minitest-handler]
- name: mongod-lwrp
  run_list:
    - recipe[hipsnip-mongodb_test::mongod_lwrp]
    - recipe[minitest-handler]
- name: replicaset-lwrp
  run_list:
    - recipe[hipsnip-mongodb_test::replica_set_lwrp]
    - recipe[minitest-handler]