---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04-nochef
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: 11.10.0
  run_list:
  - recipe[apt]

suites:
- name: mongod-recipe
  run_list:
    - recipe[hipsnip-mongodb_test::mongod_recipe]
- name: mongod-lwrp
  run_list:
    - recipe[hipsnip-mongodb_test::mongod_lwrp]
- name: replicaset-lwrp
  run_list:
    - recipe[hipsnip-mongodb_test::replica_set_lwrp]